version: "3.8"

services:

    db:
        image: mysql:5.7
        container_name: borda_db
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        expose: 
            - "3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=***
            - MYSQL_USER=***
            - MYSQL_PASSWORD=***
            - MYSQL_DATABASE=***
        volumes:
            - db_volume:/var/lib/mysql
        networks:
            - backend

    flask:
        build: ./flask
        container_name: flask_borda
        restart: always
        depends_on:
            - db
        expose:
            - "5000"
        environment: 
            - APP_DB_HOST=db
            - APP_DB_PORT=***
            - APP_DB_USER=***
            - APP_DB_PASSWORD=***
            - APP_DB_NAME=***
        networks:
            - backend

    nginx:
        build: ./nginx
        container_name: nginx_borda
        restart: always
        expose: 
            - "80"
        ports:
            - "80:80"
        networks:
            - backend

volumes:
    db_volume:

networks:
    backend: